export enum ProjectStatus {
  DRAFT = "DRAFT",
  SCRIPT_READY = "SCRIPT_READY",
  VOICE_READY = "VOICE_READY",
  LAYOUT_READY = "LAYOUT_READY",
  VISUAL_READY = "VISUAL_READY",
  CAMERA_READY = "CAMERA_READY",
  PACING_READY = "PACING_READY",
  READY_FOR_REVIEW = "READY_FOR_REVIEW",
  RENDERED = "RENDERED",
}
